spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/brecho
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
api.security.token.secret=${JWT_SECRET:my-secret-key}
upload.dir=uploads

server.url=http://localhost:8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

spring.web.resources.static-locations=classpath:/static/,file:uploads/